"""Generated workflow from agents/examples/dsl/combined.sr.

Auto-generated by Streetrace DSL Compiler.
Do not edit directly - modify the .sr source file instead.
"""
from typing import Any

import asyncio

from streetrace.dsl.runtime.context import WorkflowContext
from streetrace.dsl.runtime.workflow import DslAgentWorkflow
from streetrace.dsl.runtime.errors import (
    AbortError,
    BlockedInputError,
    RetryInputError,
    RetryStepError,
)

class AgentsExamplesDslCombinedWorkflow(DslAgentWorkflow):
    """Generated workflow from agents/examples/dsl/combined.sr."""

    _models = {
        # agents/examples/dsl/combined.sr:14
        'main': 'anthropic/claude-sonnet',
        # agents/examples/dsl/combined.sr:15
        'fast': 'anthropic/haiku',
    }

    _prompts = {
        # agents/examples/dsl/combined.sr:30
        'formatter_prompt': lambda ctx: f"""Format code according to style guidelines.
Return properly formatted code.""",
        # agents/examples/dsl/combined.sr:37
        'linter_prompt': lambda ctx: f"""Check code for common errors and style issues.
Return list of findings.""",
        # agents/examples/dsl/combined.sr:44
        'security_scanner_prompt': lambda ctx: f"""Scan code for security vulnerabilities.
Focus on injection, XSS, auth issues.""",
        # agents/examples/dsl/combined.sr:53
        'code_reviewer_prompt': lambda ctx: f"""You are a code reviewer.
Use the formatter, linter, and security_scanner tools to
thoroughly review code. Synthesize findings into a review.""",
        # agents/examples/dsl/combined.sr:63
        'doc_writer_prompt': lambda ctx: f"""Write documentation for code.
Create clear, comprehensive documentation.""",
        # agents/examples/dsl/combined.sr:73
        'coordinator_prompt': lambda ctx: f"""You are a development team coordinator.
Delegate tasks to the appropriate specialist:
- Code review tasks go to code_reviewer
- Documentation tasks go to doc_writer

Ensure all work meets quality standards before completion.""",
        # agents/examples/dsl/combined.sr:90
        'review_check': lambda ctx: f"""Evaluate the work product.
Score from 0-100, list any feedback items, approve if score >= 85.""",
    }

    _prompt_models = {
        # agents/examples/dsl/combined.sr:73
        'coordinator_prompt': 'fast',
    }

    _tools = {
        # agents/examples/dsl/combined.sr:22
        'fs': {'type': 'builtin', 'url': None},
        # agents/examples/dsl/combined.sr:23
        'web': {'type': 'builtin', 'url': None},
    }

    _agents = {
        # agents/examples/dsl/combined.sr:33
        'formatter': {
            'tools': [],
            'instruction': 'formatter_prompt',
        },
        # agents/examples/dsl/combined.sr:40
        'linter': {
            'tools': [],
            'instruction': 'linter_prompt',
        },
        # agents/examples/dsl/combined.sr:47
        'security_scanner': {
            'tools': [],
            'instruction': 'security_scanner_prompt',
        },
        # agents/examples/dsl/combined.sr:57
        'code_reviewer': {
            'tools': ['fs'],
            'instruction': 'code_reviewer_prompt',
            'agent_tools': ['formatter', 'linter', 'security_scanner'],
        },
        # agents/examples/dsl/combined.sr:66
        'doc_writer': {
            'tools': ['fs'],
            'instruction': 'doc_writer_prompt',
        },
        # agents/examples/dsl/combined.sr:80
        'default': {
            'tools': ['fs'],
            'instruction': 'coordinator_prompt',
            'sub_agents': ['code_reviewer', 'doc_writer'],
        },
    }

    # agents/examples/dsl/combined.sr:93
    async def flow_quality_loop(self, ctx: WorkflowContext) -> Any:
        ctx.vars['current'] = ctx.vars['work']
        # agents/examples/dsl/combined.sr:97
        _loop_count = 0
        _max_iterations = 3
        while _loop_count < _max_iterations:
            _loop_count += 1
            # agents/examples/dsl/combined.sr:98
            ctx.vars['current'] = await ctx.call_llm('review_check', ctx.vars['current'])
            ctx.log('log')
        # agents/examples/dsl/combined.sr:102
        return {"result": ctx.vars['current']}

