#!/bin/bash
# Format code review results for PR comment

if [ -f "code-review-result.md" ]; then
    {
        echo "## 🔍 StreetRace Code Review"
        echo ""
        cat code-review-result.md
        echo ""
        echo "---"
        echo "*Review generated by [StreetRace](https://github.com/streetrace-ai/streetrace) AI*"
    } > formatted-review.md
else
    {
        echo "## 🔍 StreetRace Code Review"
        echo ""
        echo "# Code Review Failed"
        echo ""
        echo "The code review could not be completed. Please check the workflow logs for more details."
        echo ""
        echo "---"
        echo "*Review generated by [StreetRace](https://github.com/streetrace-ai/streetrace) AI*"
    } > formatted-review.md
fi