"""Generated workflow from agents/examples/workloads/delegate_pattern.sr.

Auto-generated by Streetrace DSL Compiler.
Do not edit directly - modify the .sr source file instead.
"""
from typing import Any

import asyncio

from streetrace.dsl.runtime.context import WorkflowContext
from streetrace.dsl.runtime.workflow import DslAgentWorkflow
from streetrace.dsl.runtime.errors import (
    AbortError,
    BlockedInputError,
    RetryInputError,
    RetryStepError,
)

class AgentsExamplesWorkloadsDelegatePatternWorkflow(DslAgentWorkflow):
    """Generated workflow from agents/examples/workloads/delegate_pattern.sr."""

    _models = {
        # agents/examples/workloads/delegate_pattern.sr:4
        'main': 'anthropic/claude-sonnet-4-5',
    }

    _prompts = {
        # agents/examples/workloads/delegate_pattern.sr:13
        'coordinator_prompt': lambda ctx: f"""You are a coordinator. For technical questions, delegate to the specialist.
If asked about Python async, immediately delegate to the specialist.""",
        # agents/examples/workloads/delegate_pattern.sr:16
        'specialist_prompt': lambda ctx: f"""You are a Python async specialist. Provide expert answers about async/await.
Be very concise - one sentence only.""",
    }

    _prompt_models: dict[str, str] = {}

    _tools: dict[str, dict[str, Any]] = {}

    _agents = {
        # agents/examples/workloads/delegate_pattern.sr:6
        'coordinator': {
            'tools': [],
            'instruction': 'coordinator_prompt',
            'sub_agents': ['specialist'],
        },
        # agents/examples/workloads/delegate_pattern.sr:10
        'specialist': {
            'tools': [],
            'instruction': 'specialist_prompt',
        },
    }

    # agents/examples/workloads/delegate_pattern.sr:19
    async def flow_main(self, ctx: WorkflowContext) -> Any:
        # agents/examples/workloads/delegate_pattern.sr:20
        await ctx.run_agent('coordinator', ctx.vars['input_prompt'])

