"""AST module for Streetrace DSL.

Provide AST node dataclasses and the transformer that converts
Lark parse trees into typed AST structures.
"""

from streetrace.dsl.ast.nodes import (
    AgentDef,
    Assignment,
    BinaryOp,
    BlockAction,
    CallStmt,
    DslFile,
    EscalateStmt,
    EventHandler,
    FailureBlock,
    FlowDef,
    ForLoop,
    FunctionCall,
    IfBlock,
    ImportStmt,
    ListLiteral,
    Literal,
    LogStmt,
    MaskAction,
    MatchBlock,
    MatchCase,
    ModelDef,
    ObjectLiteral,
    ParallelBlock,
    PolicyDef,
    PromptDef,
    PropertyAccess,
    PushStmt,
    RetryAction,
    RetryPolicyDef,
    ReturnStmt,
    RunStmt,
    SchemaDef,
    SchemaField,
    SourcePosition,
    TimeoutPolicyDef,
    ToolDef,
    TypeExpr,
    UnaryOp,
    VarRef,
    VersionDecl,
    WarnAction,
)
from streetrace.dsl.ast.transformer import transform

__all__ = [
    "AgentDef",
    "Assignment",
    "BinaryOp",
    "BlockAction",
    "CallStmt",
    "DslFile",
    "EscalateStmt",
    "EventHandler",
    "FailureBlock",
    "FlowDef",
    "ForLoop",
    "FunctionCall",
    "IfBlock",
    "ImportStmt",
    "ListLiteral",
    "Literal",
    "LogStmt",
    "MaskAction",
    "MatchBlock",
    "MatchCase",
    "ModelDef",
    "ObjectLiteral",
    "ParallelBlock",
    "PolicyDef",
    "PromptDef",
    "PropertyAccess",
    "PushStmt",
    "RetryAction",
    "RetryPolicyDef",
    "ReturnStmt",
    "RunStmt",
    "SchemaDef",
    "SchemaField",
    "SourcePosition",
    "TimeoutPolicyDef",
    "ToolDef",
    "TypeExpr",
    "UnaryOp",
    "VarRef",
    "VersionDecl",
    "WarnAction",
    "transform",
]
